<?php if ( ! defined( 'ABSPATH' ) ) exit; global $wpdb; $scoring = new QM2026_Scoring(); $pool_id=(int)$wpdb->get_var('SELECT id FROM '.qm2026_table('pools').' ORDER BY id LIMIT 1'); ?>
<div class="wrap qm2026"><h1><?php esc_html_e('Quiniela Mundialista 2026', QM2026_TEXT_DOMAIN); ?></h1><?php if(!empty($_GET['qm2026_notice'])) echo '<div class="notice notice-success"><p>'.esc_html(wp_unslash($_GET['qm2026_notice'])).'</p></div>'; ?>
<div class="qm2026-grid">
<div class="qm2026-card"><strong><?php esc_html_e('Participantes', QM2026_TEXT_DOMAIN); ?></strong><span><?php echo esc_html($wpdb->get_var('SELECT COUNT(*) FROM '.qm2026_table('participants'))); ?></span></div>
<div class="qm2026-card"><strong><?php esc_html_e('Partidos jugados', QM2026_TEXT_DOMAIN); ?></strong><span><?php echo esc_html($wpdb->get_var("SELECT COUNT(*) FROM ".qm2026_table('matches')." WHERE status='finished'")); ?></span></div>
<div class="qm2026-card"><strong><?php esc_html_e('Predicciones', QM2026_TEXT_DOMAIN); ?></strong><span><?php echo esc_html($wpdb->get_var('SELECT COUNT(*) FROM '.qm2026_table('predictions'))); ?></span></div>
<div class="qm2026-card"><strong><?php esc_html_e('Sin resultado', QM2026_TEXT_DOMAIN); ?></strong><span><?php echo esc_html($wpdb->get_var("SELECT COUNT(*) FROM ".qm2026_table('matches')." WHERE match_datetime < NOW() AND status <> 'finished'")); ?></span></div>
</div>
<h2><?php esc_html_e('Top 10', QM2026_TEXT_DOMAIN); ?></h2><?php $ranking=$pool_id?$scoring->ranking($pool_id,10):array(); include QM2026_PATH.'public/views/ranking.php'; ?>
<h2><?php esc_html_e('Próximos partidos', QM2026_TEXT_DOMAIN); ?></h2><table class="widefat"><thead><tr><th>#</th><th><?php esc_html_e('Partido', QM2026_TEXT_DOMAIN); ?></th><th><?php esc_html_e('Fecha', QM2026_TEXT_DOMAIN); ?></th></tr></thead><tbody><?php foreach($wpdb->get_results('SELECT m.*,ht.name h,at.name a FROM '.qm2026_table('matches').' m LEFT JOIN '.qm2026_table('teams').' ht ON ht.id=m.home_team_id LEFT JOIN '.qm2026_table('teams').' at ON at.id=m.away_team_id WHERE status="scheduled" ORDER BY match_datetime LIMIT 8') as $m): ?><tr><td><?php echo esc_html($m->fifa_match_no); ?></td><td><?php echo esc_html(($m->h?:$m->home_placeholder).' vs '.($m->a?:$m->away_placeholder)); ?></td><td><?php echo esc_html($m->match_datetime); ?></td></tr><?php endforeach; ?></tbody></table></div>
